%%
clc;    clear;      close all;
ryzyko_zawalu_FIS = readfis('ryzykozawalu.fis');   
chwilowe_prawdopodobienstwo_zawalu_FIS = readfis('chwilowe_prawdopodobienstwo_zawalu.fis');

%Du¿e ryzyko zawa³u
Patient_1 = struct(...
'system1', struct(...
    'plec', 0, ... %mezczyzna
    'palenie_tytoniu', 0.884 , ... %bardzo czêsto
    'waga', 0.854 , ...  % pomiedzy nadwag¹, a oty³oœci¹
    'kamienie_piersia', 0, ... % nie dotyczy
    'status_matrymonialny', 0.93 , ... % rozwiedziony
    'zatrudnienie', 0.3, ... % nie pracuje
    'socjoekonomiczne_warunki_wychowania', 0 , ... % nie dotyczy
    'cisnienie_krwi', 0.95, ... % wysokie
    'ruch', 0.06 , ... % skrajnie ma³o
    'cukrzyca', 0.90 ... %wystepuje
    ), ... 
 'system2', struct(...
    'ryzyko', 0.9, ...
    'stresujaca_sytuacja', 0.9, ...
    'bol_klatki', 0.9, ...
    'bol_ramienia', 0.9, ...
    'plytki_oddech', 0.9));

%Œrednie ryzyko zawa³u
Patient_2 = struct(...
'system1', struct(...
    'plec', 0, ... % mezczyzna
    'palenie_tytoniu', 0.4392 , ...
    'waga', 0.4392 , ... 
    'kamienie_piersia', 0, ...
    'status_matrymonialny', 0.5 , ...
    'zatrudnienie', 0.6419, ...
    'socjoekonomiczne_warunki_wychowania', 0 , ...
    'cisnienie_krwi', 0.5, ...
    'ruch', 0.6149 , ...
    'cukrzyca', 0.3986 ...
    ), ...
 'system2', struct(...
    'ryzyko', 0, ...
    'stresujaca_sytuacja', 0, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0, ...
    'plytki_oddech', 0));

%Ma³e ryzyko zwa³u
Patient_3 = struct(...
'system1', struct(...
    'plec', 0, ...
    'palenie_tytoniu', 0.06081 , ...
    'waga', 0.3581 , ... 
    'kamienie_piersia', 0, ...
    'status_matrymonialny', 0.5 , ...
    'zatrudnienie', 0.6419, ...
    'socjoekonomiczne_warunki_wychowania', 0 , ...
    'cisnienie_krwi', 0.5, ...
    'ruch', 0.8986 , ...
    'cukrzyca', 0.3986 ...
    ), ...
 'system2', struct(...
    'ryzyko', 0, ...
    'stresujaca_sytuacja', 0, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0, ...
    'plytki_oddech', 0));

[output_ryzyko1]=evalfis(GetAllPatientPropsInArray(Patient_1.system1),ryzyko_zawalu_FIS);
[output_ryzyko2]=evalfis(GetAllPatientPropsInArray(Patient_2.system1),ryzyko_zawalu_FIS);
[output_ryzyko3]=evalfis(GetAllPatientPropsInArray(Patient_3.system1),ryzyko_zawalu_FIS);

[output_chwilowe_prawdopodobienstwo]=evalfis(GetAllPatientPropsInArray(Patient_1.system2),chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo2]=evalfis(GetAllPatientPropsInArray(Patient_2.system2),chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo3]=evalfis(GetAllPatientPropsInArray(Patient_3.system2),chwilowe_prawdopodobienstwo_zawalu_FIS);