%%
clc;    clear;      close all;
ryzyko_zawalu_FIS = readfis('ryzykozawalu.fis');   
chwilowe_prawdopodobienstwo_zawalu_FIS = readfis('chwilowe_prawdopodobienstwo_zawalu.fis');

%Du¿e ryzyko zawa³u
Patient_1 = struct(...
'system1', struct(...
    'plec', 0, ... 
    'palenie_tytoniu', 0.884 , ... 
    'waga', 0.854 , ...  
    'kamienie_piersia', 0, ... % nie dotyczy
    'status_matrymonialny', 0.93 , ... 
    'zatrudnienie', 0.3, ... 
    'socjoekonomiczne_warunki_wychowania', 0 , ... % nie dotyczy
    'cisnienie_krwi', 0.95, ... 
    'ruch', 0.06 , ... 
    'cukrzyca', 0.90 ... 
    ), ... 
 'system2', struct(...
    'stresujaca_sytuacja', 0.1, ...
    'bol_klatki', 0.9, ...
    'bol_ramienia', 0.5, ...
    'plytki_oddech', 0.5));

%Œrednie ryzyko zawa³u
Patient_2 = struct(...
'system1', struct(...
    'plec', 0, ... % mezczyzna
    'palenie_tytoniu', 0.4392 , ...
    'waga', 0.4392 , ... 
    'kamienie_piersia', 0, ... % nie dotyczy
    'status_matrymonialny', 0.5 , ...
    'zatrudnienie', 0.6419, ...
    'socjoekonomiczne_warunki_wychowania', 0 , ... % nie dotyczy
    'cisnienie_krwi', 0.5, ...
    'ruch', 0.6149 , ...
    'cukrzyca', 0.3986 ...
    ), ...
 'system2', struct(...
    'stresujaca_sytuacja', 0.9, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0, ...
    'plytki_oddech', 0));

%Ma³e ryzyko zwa³u
Patient_3 = struct(...
'system1', struct(...
    'plec', 0, ...
    'palenie_tytoniu', 0.06081 , ...
    'waga', 0.3581 , ... 
    'kamienie_piersia', 0, ... % nie dotyczy
    'status_matrymonialny', 0.5 , ...
    'zatrudnienie', 0.6419, ...
    'socjoekonomiczne_warunki_wychowania', 0 , ... % nie dotyczy
    'cisnienie_krwi', 0.5, ... 
    'ruch', 0.8986 , ...
    'cukrzyca', 0.3986 ...
    ), ...
 'system2', struct(...
    'stresujaca_sytuacja', 0.9, ...
    'bol_klatki', 0.4, ...
    'bol_ramienia', 0, ...
    'plytki_oddech', 0));

%Du¿e ryzyko zawa³u
Patient_4 = struct(...
'system1', struct(...
    'plec', 1, ... 
    'palenie_tytoniu', 0.965 , ...
    'waga', 0.9557 , ... 
    'kamienie_piersia', 0.18, ... 
    'status_matrymonialny', 0 , ... % nie dotyczy
    'zatrudnienie', 0, ... % nie dotyczy
    'socjoekonomiczne_warunki_wychowania', 0.965 , ... 
    'cisnienie_krwi', 0.95, ...
    'ruch', 0.02 , ... 
    'cukrzyca', 0.92 ... 
    ), ... 
 'system2', struct(...
    'stresujaca_sytuacja', 0, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0.4, ...
    'plytki_oddech', 0.5));
 
%Œrednie ryzyko zawa³u
Patient_5 = struct(...
'system1', struct(...
    'plec', 1, ... 
    'palenie_tytoniu', 0.4592 , ...
    'waga', 0.59 , ... 
    'kamienie_piersia', 0.18, ...
    'status_matrymonialny', 0 , ... % nie dotyczy
    'zatrudnienie', 0, ... % nie dotyczy
    'socjoekonomiczne_warunki_wychowania', 0.13 , ...
    'cisnienie_krwi', 0.445, ...
    'ruch', 0.89 , ...
    'cukrzyca', 0.21 ...
    ), ...
 'system2', struct(...
    'stresujaca_sytuacja', 0.6, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0, ...
    'plytki_oddech', 0));

%Ma³e ryzyko zwa³u
Patient_6 = struct(...
'system1', struct(...
    'plec', 1, ...
    'palenie_tytoniu', 0.072 , ...
    'waga', 0.481 , ... 
    'kamienie_piersia', 0.8, ...
    'status_matrymonialny', 0 , ... % nie dotyczy
    'zatrudnienie', 0, ... % nie dotyczy
    'socjoekonomiczne_warunki_wychowania', 0 , ...
    'cisnienie_krwi', 0.54, ...
    'ruch', 0.91 , ...
    'cukrzyca', 0.3894 ...
    ), ...
 'system2', struct(...
    'stresujaca_sytuacja', 0.3, ...
    'bol_klatki', 0, ...
    'bol_ramienia', 0.6, ...
    'plytki_oddech', 0));

[output_ryzyko1]=evalfis(GetAllPatientPropsInArray(Patient_1.system1),ryzyko_zawalu_FIS);
[output_ryzyko2]=evalfis(GetAllPatientPropsInArray(Patient_2.system1),ryzyko_zawalu_FIS);
[output_ryzyko3]=evalfis(GetAllPatientPropsInArray(Patient_3.system1),ryzyko_zawalu_FIS);
[output_ryzyko4]=evalfis(GetAllPatientPropsInArray(Patient_4.system1),ryzyko_zawalu_FIS);
[output_ryzyko5]=evalfis(GetAllPatientPropsInArray(Patient_5.system1),ryzyko_zawalu_FIS);
[output_ryzyko6]=evalfis(GetAllPatientPropsInArray(Patient_6.system1),ryzyko_zawalu_FIS);

[output_chwilowe_prawdopodobienstwo]=evalfis([output_ryzyko1; GetAllPatientPropsInArray(Patient_1.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo2]=evalfis([output_ryzyko2;GetAllPatientPropsInArray(Patient_2.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo3]=evalfis([output_ryzyko3;GetAllPatientPropsInArray(Patient_3.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo4]=evalfis([output_ryzyko4;GetAllPatientPropsInArray(Patient_4.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo5]=evalfis([output_ryzyko5;GetAllPatientPropsInArray(Patient_5.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);
[output_chwilowe_prawdopodobienstwo6]=evalfis([output_ryzyko6;GetAllPatientPropsInArray(Patient_6.system2)],chwilowe_prawdopodobienstwo_zawalu_FIS);